### PR TITLE
Recover EventSubscriberTransformer, Enable private event subscriber.

### PR DESCRIPTION
**Pull request by Ecdcaeb**
Since the cost has been cost. Why we do not make it public, but throw a error?

### CODE REVIEW

**Comment by Ecdcaeb** [comment]
To take a step back, even if this is not supported, we should not throw directly in the Transformer, otherwise it will be mistaken for file corruption. //ClassDefNotFound

**Comment by kappa-maintainer** [comment]
In my opinion, a runtime error exists to remind careless developers in dev, not in production
Yes we are babysitting mods, but that's a new level of babysitting

**Comment by Ecdcaeb** [comment]
Since this, Just move it to `CleanroomGradle`. The checks go in development environment. Avoid the cost in real environment.

**Comment by Ecdcaeb** [comment]
Either the `EventSubscriberTransformer` is moved or it is working properly and there shouldn't be a third case here.

**Comment by Ecdcaeb** [comment]
It's also good to keep the subscriber private to prevent accidental external calls. But modifying it to public may be expensive, which is my only concern, but now that we have spent it, we should make it effective. Once Bouncepad successfully provides ClassNode, the overhead here can be ignored.

**Comment by kappa-maintainer** [comment]
1. CG can't check source (or errors) at this level, that's not how normal gradle plugin work
2. The cost here is far lower than you imagine. I have seen ppl do all kinds of stupid thing in transformers, but impact on launch time is far from noticeable
3. You can't prevent calls by just `private`, and worrying about accidentally call to a method require an event instance (in fxxking runtime) make no sense. 
4. No, read every class to classnode everywhere is far from expensive.  `toPublic` is just bit manipulation, and we already have a few global remapper and redirector here.
5. Bouncepad may or may not provide classnode. I am checking other byte code libraries, they need regular byte array.
6. Could you please post everything once?

**Comment by Ecdcaeb** [comment]
- Since According to what you said, there is nothing wrong with `Recover EventSubscriberTransformer`.
- Sending the content that comes to my mind in sections without buffering is a habit I picked up elsewhere. It was only when you mentioned it that I remembered your email status.
- `But modifying it to public may be expensive` means `EventSubscriberTransformer`'s work on every classes.
- a new level of babysitting is not worse, we already have one.

**Comment by Rongmario** [comment]
I'm gonna close this, we'll revisit this when the [events proposal](https://github.com/CleanroomMC/Cleanroom/discussions/79) finalizes as it is likely we will rewrite the backend of events registration and class generation.

**Pull request closed without merging**
