### PR TITLE
Obliterated ASMClassLoader

### PR DESCRIPTION
**Pull request by Ecdcaeb**
Good bye ASMClassLoader, you have done good job back then

### CODE REVIEW

**Comment by kappa-maintainer** [comment]
I am adding a `defineClass()` in LaunchClassLoader directly, since many methods in unsafe will be gone, and they want people to define class in lookup.
You could move the deep search part to another pull request though

**Comment by Ecdcaeb** [comment]
I am waiting for pr https://github.com/kappa-maintainer/Bouncepad-cursed/pull/1

**Comment by kappa-maintainer** [comment]
Checked my inbox and found your PR did not get delivered by GitHub, I guess something gone wrong in mailing setting
What I am testing is in another repository, but I don't see harm to merge it
As for this PR, you could change it or close it

**Comment by Ecdcaeb** [comment]
```discord
Hileb
Oh no, the field is LaunchClassLoader.
((BouncepadClassLoader)Bouncepad.classLoader).defineClass(name, clazz);
geeky_kappa
too stupid
Just changed LCL itself
```

/o~o/

**Pull request closed without merging**
