### PR TITLE
Fix and Update the Installer

### PR DESCRIPTION
**Pull request by Ecdcaeb**
# Why this pr here
**The existing installer is missing the licenses!**
**The existing installer icon is incorrect!**

# What this pr brings
#### Forge
image

#### Cleanroom 3029
image

#### This PR
image

`url` is not imported by this pr.

### Icon
image

from twitter,  remove the background to adapt the install theme.

### CODE REVIEW

**Comment by ZZZank** [comment]
The icon looks bad (due to its rough edges), I will recommend using the original icon, but with corners rounded

**Comment by Ecdcaeb** [comment]
> The icon looks bad (due to its rough edges), I will recommend using the original icon, but with corners rounded

Yes, I don't have the original image of it. I will ask rong for the original image or process it carefully.

**Comment by Rongmario** [comment]
> > The icon looks bad (due to its rough edges), I will recommend using the original icon, but with corners rounded
> 
> Yes, I don't have the original image of it. I will ask rong for the original image or process it carefully.

Use [this one](https://github.com/CleanroomMC/Resources/blob/master/Art/cleanroom-logo.png), I believe an icon is enough, the text "Cleanroom" can be left out.

**Review by Rongmario — CHANGES_REQUESTED** [review]
Change `CREDITS.txt` to `FORGE-CREDITS.txt` and use the icon png from the Resources repository.

**Review by Ecdcaeb — COMMENTED** [review]
Oh, a large icon!
image

**Review by Rongmario — CHANGES_REQUESTED** [review]
Scale the image down, so that the installer can be smaller like its original size.

**Comment by Ecdcaeb** [comment]
Forge Installer do not support scaling for image. I make a version of 64.

**Comment by Ecdcaeb** [comment]
change to neoforge installer
image
but the field of icon is invalid, use https://github.com/neoforged/LegacyInstaller/blob/main/src/main/java/net/minecraftforge/installer/ui/Images.java#L31

TODO: find out how to replace it

**Comment by Ecdcaeb** [comment]
due to https://github.com/neoforged/LegacyInstaller/pull/34#issuecomment-2425937887
I have done my best. Use it? Fork it?
Ready for rewiew

**Comment by Rongmario** [comment]
Is there a reason why NeoForge's installer tools is used instead?

**Comment by Ecdcaeb** [comment]
> Is there a reason why NeoForge's installer tools is used instead?

More support will be available. The MinecraftForge Installer is updated slowly.

**Comment by KorewaLidesu** [comment]
I don't think there is much change on NeoForge fork to consider switching since most of features already completed.
If the later development of CRL required a change on Installer, we will consider switch or create new one instead.

**Comment by Ecdcaeb** [comment]
> I don't think there is much change on NeoForge fork to consider switching since most of features already completed. If the later development of CRL required a change on Installer, we will consider switch or create new one instead.

This PR has been stagnant for a while, and `LegacyInstaller` can do all my needs. With my meager wisdom, I can't foresee the disadvantages here. I can only see the benefits of the conversion and the pleasing new features, while I can't understand why this change is unpleasant.

**Comment by KorewaLidesu** [comment]
Seem good, just move the icons to separate folder and I will check out for merging.

**Comment by Ecdcaeb** [comment]
`https://github.com/neoforged/LegacyInstaller/issues/36`

**Comment by Ecdcaeb** [comment]
1.12.2 lacks official mapping, which will cause an exception when making an offline fat installer containing the mc body. https://github.com/neoforged/LegacyInstaller/blob/f4d8f3fae5e0497732dac454232aeac70dabb786/src/main/java/net/minecraftforge/installer/actions/FatInstallerAction.java#L65

**Comment by Ecdcaeb** [comment]
Done

**Review by KorewaLidesu — APPROVED** [review]
LGTM.

**Pull request merged**
