### PR TITLE
PoseEvent

### PR DESCRIPTION
**Pull request by Ecdcaeb**
I test it and make a ExampleMod. Player nodding fastly and successfully.

### CODE REVIEW

**Comment by KorewaLidesu** [comment]
Can you directly patch instead of using ASM?
Or it is used in case of other mods usage on the method?

**Comment by Ecdcaeb** [comment]
> Can you directly patch instead of using ASM? Or it is used in case of other mods usage on the method?

no. The abstract transformation is needed. Since we don't know how many Model there are and how complexly they override and super.

**Comment by KorewaLidesu** [comment]
> no. The abstract transformation is needed. Since we don't know how many Model there are and how complexly they override and super.

I'm abit concern for the transformation interface, use the exist one from Bouncepad would not hurt?

**Comment by Ecdcaeb** [comment]
My [Bouncepad](https://github.com/CleanroomMC/Bouncepad) may be outdated.

**Comment by kappa-maintainer** [comment]
We are currently using my cursed fork to patch ASM api version crash, here
https://github.com/kappa-maintainer/Bouncepad-cursed/

**Comment by kappa-maintainer** [comment]
Why you are adding another classloader? We already have enough trouble from two of them

**Comment by Ecdcaeb** [comment]
> Why you are adding another classloader? We already have enough trouble from two of them

I want to get a public one...

**Comment by kappa-maintainer** [comment]
*Sigh*
You won't get anything merged if you don't write down why and how clearly

**Comment by kappa-maintainer** [comment]
Writing ASM to transform vanilla in Cleanroom? That's another level now. If you don't clarify what you are doing and why, I will close the pull request.

**Comment by Ecdcaeb** [comment]
> Writing ASM to transform vanilla in Cleanroom? That's another level now. If you don't clarify what you are doing and why, I will close the pull request.
 The abstract transformation is needed.
I cannot simply use patches because they do not apply to non vanilla content. This Transformer can not only modify vanilla, but also widely modify Mod.

**Comment by KorewaLidesu** [comment]
This is a bit awkward, but please knowing with the goal of Cleanroom is to eliminate any hackery solutions from mods, I think this PR isn't suit for that purpose.
And for the Transformer, please ensure that, you are using the one and only one from Bouncepad. As it is the only way should ever coremodding should centralize on, before we have a properly API that allow us not to manipulate bytecode (which can sometimes lead to horrible issue upon debugging).

**Comment by kappa-maintainer** [comment]
I read your changes a bit, here's the problem:
- adding new event and new coremod changes should be in two pull request
- Please use defineClass in internal unsafe or MethodHandles, new classloader could cause different instances in different classloaders, sometimes could crash the game since LauncClassLoader load class by searching for actual .class file
- No, we won't introduce breaking API changes before community back. Adding more and more transformer is not in our plan too. Please figure out a smart way to add new logic.

**Comment by Ecdcaeb** [comment]
Yes, I will figure out a smart way to add new logic.

**Comment by Ecdcaeb** [comment]
There is no better way here. Using patches will limit its functionality, while Transformation is not allowed.
Therefore, this Event will not be added.
If Modder needs to modify actions, use Mixin freely.(x

**Comment by Rongmario** [comment]
I'll reopen this, when I have time I can review it. But first, may I ask what the reasoning is behind such an event?

**Comment by Ecdcaeb** [comment]
The existing rendering events cannot change the pose of the entity.
If we cancel it and then take over rendering, it would be too breaking.
Therefore, many Mods need to hack into the `Model` if they want to modify the pose of the entity.
Therefore, I would like to add an event to post after setting the physical pose but before rendering, to give Modder the opportunity to modify the pose.
However, the `ModelBase` of vanilla (including the module) is too complex, so it cannot be completed with a simple and specific `patches`. I used the abstraction of `IClassTransformer` to accomplish it, but it goes against the Cleanroom philosophy.
Besides, I don't know how to follow up on the version of Bouncepad to use `Transformer`

**Comment by Rongmario** [comment]
Do you have an example of a hack for the `Model`? I want to see it so I can understand your approach, thank you!

**Comment by Rongmario** [comment]
I understand and have a general idea now, I'll write a plan of what I have later today or tomorrow. Essentially, the transformation will have to redirect existing calls in `ModelBase` and more.

Method in `ModelBase` and some of the extensions like `ModelBiped` should have Pre/Post events.

For example in `ModelBase.class`:

```diff
+public final void cleanroom$setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn)
{
+    var event = new Pre.RenderEntitySetRotationEvent(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor));
+    MinecraftForge.EVENT_BUS.post(event);
+    limbSwing = event.getLimbSwing(); // Reassign variables from event
+    this.setRotationAngles(limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor, entityIn);
+    var event = new Post.RenderEntitySetRotationEvent(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor));
+    MinecraftForge.EVENT_BUS.post(event); // Don't reassign variables, as there is no need
}

+ // For overriding, change visibility of it so it can't (discourage to) be called, and redirect existing calls to this method to the one above
+protected void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, +float +headPitch, float scaleFactor, Entity entityIn)
+{
+
+}

```

**Pull request closed without merging**
